### ISSUE TITLE
Main Configuration File Problem: brave-portable.yml

### ISSUE THREAD

**Issue by STSMHQ** [portapps/brave-portable#106]
#### Steps to reproduce this issue

1. Run the brave portable app for the first time.
2. Rename the main configuration file to `brave-portable.yml`
3. Run the brave portable app again.

#### Expected behaviour

The changed configurations in the YAML file should be considered.

#### Actual behaviour

The changed configurations in the YAML file aren't considered.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : brave-portable-win64-1.34.80-80.

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 11 Pro 64 bits.

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

My `brave-portable.yml` file:

![image](https://user-images.githubusercontent.com/94048176/166221827-b7881fa4-d0fb-447e-835e-ad59ed88052e.png)

### Logs

The important stuff from the logs:

```
Mon, 02 May 2022 11:33:33 BST INF C:/Users/runneradmin/go/pkg/mod/github.com/portapps/portapps/v3@v3.4.0/portapps.go:127 > Configuration:
common:
  disable_log: false
  args: []
  env: {}
  app_path: ""
app:
  cleanup: true
  disable_telemetry: true
  multiple_instances: true
  profile: default
```

The logs show that the configuration that I've is considered, but I can't open multiple instances of brave and the cleanup doesn't work, cause when I open the brave the next time.. things from the previous session are still there.
