### ISSUE TITLE
Feature request: Config for user data directory

### ISSUE THREAD

**Issue by Nezteb** [portapps/brave-portable#154]
It looks like the app currently doesn't allow you to set the data directory:

https://github.com/portapps/brave-portable/blob/2f22c0c62309d0319138086afed5497852fd87d6/main.go#L42-L63

It'd be nice if we could choose where that data is stored, including in the install directory of the portable app itself. This seems like a good candidate for a config item perhaps? Example:

```yaml
app:
  cleanup: false
  user_data_dir: 'C:\portapps\brave-portable\data\user'
```

This is somewhat related to [an existing issue](https://github.com/portapps/brave-portable/issues/146), but I wanted to phrase this as more of a feature request than an inquiry. 😄
